image: Visual Studio 2017
build_script:
- ps: >-
    [xml]$doc = (Get-Content .\DeviceIOControlLib\DeviceIOControlLib.csproj)

    [string]$version = $doc.Project.PropertyGroup.Version
    
    Update-AppveyorBuild -Version "$($version.Trim()).$env:APPVEYOR_BUILD_NUMBER"
- ps: # Library
- ps: msbuild /t:Build /p:Configuration=Release DeviceIOControlLib
- ps: # Pack Library
- ps: msbuild /t:Pack /p:Configuration=Release DeviceIOControlLib
- ps: # Utilities
- ps: msbuild /t:Build /p:Configuration=Release DemoApplication
install:
- msbuild /t:Restore
artifacts:
- path: DeviceIOControlLib\bin\Release\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: cvr8JbPstt1PUf5UKu9QpY1b31wQUwzwofPxLyoq5PxYRTjEivrWQBEJlijQrqbi
  on:
    branch: nuget